apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  api_key: <base64-encoded-api-key>
  api_secret: <base64-encoded-api-secret>
  bootstrap_server: <base64-encoded-bootstrap-server>

