apiVersion: v1
kind: Secret
metadata:
  name: kafka-client-properties
  namespace: kafka
type: Opaque
data:
  client.properties: c2VjdXJpdHkucHJvdG9jb2w9U0FTTF9QTEFJTlRFWFQKc2FzbC5tZWNoYW5pc209U0NSQU0tU0hBLTI1NgpzYXNsLmphYXMuY29uZmlnPW9yZy5hcGFjaGUua2Fma2EuY29tbW9uLnNlY3VyaXR5LnNjcmFtLlNjcmFtTG9naW5Nb2R1bGUgcmVxdWlyZWQgdXNlcm5hbWU9InVzZXIxIiBwYXNzd29yZD0iVHh1ajRuZDVSYiI7Cgo=
  username: dXNlcjE=
  password: VHh1ajRuZDVSYg==

